import streamlit as st
import pandas as pd
import numpy as np
import joblib
import json
import os
import base64
from datetime import timedelta

# ==========================================
# 1. APP CONFIGURATION
# ==========================================
st.set_page_config(
    page_title="Seafood Security Simulator",
    layout="wide",
    page_icon="🐟"
)

# ==========================================
# 2. MODEL LOADER (STRUCTURAL + METRICS)
# ==========================================
@st.cache_resource
def load_resources():
    """
    Loads the Champion EBMs and their Forensic Audit Scores.
    Uses caching to prevent reloading large files on every slider move.
    """
    # Defaults (Fallbacks based on our known results)
    k_stats = {'Accuracy': '96.76', 'MAPE': '3.2', 'Structural_MAE': '0.54'}
    s_stats = {'Accuracy': '97.11', 'MAPE': '2.9', 'Structural_MAE': '0.53'}
    
    try:
        # Load Structural Brains
        k_struct = joblib.load('kembung_structural_model.pkl')
        s_struct = joblib.load('selar_structural_model.pkl')
        
        # Load Forensic Metrics (generated by our audit script)
        if os.path.exists('kembung_metrics.json'):
            with open('kembung_metrics.json', 'r') as f: k_stats = json.load(f)
        if os.path.exists('selar_metrics.json'):
            with open('selar_metrics.json', 'r') as f: s_stats = json.load(f)
            
        return k_struct, s_struct, k_stats, s_stats

    except Exception as e:
        st.error(f"❌ Critical Error Loading Resources: {e}")
        # Return Nones so the app stops gracefully
        return None, None, k_stats, s_stats

# Load and Unpack EXACTLY 4 items into memory
k_struct, s_struct, k_stats, s_stats = load_resources()

# Safety Check: Stop if models are missing
if k_struct is None:
    st.warning("⚠️ Model files not found. Please ensure .pkl files are in the directory.")
    st.stop()

# ==========================================
# 3. SIDEBAR & NAVIGATION
# ==========================================
with st.sidebar:
    st.title("Main Menu")
    # The Global Selector that controls the whole app
    species_choice = st.radio("Select Species:", ["🐟 Kembung", "🐠 Selar"])
    
    st.divider()
    
    # System Status Panel
    st.info("System Architecture")
    if "Kembung" in species_choice:
        st.caption("Mode: Benchmark Beater")
        st.caption("Config: 6 Structural Features")
        st.caption("Target: Domestic Stability")
    else:
        st.caption("Mode: Surgical Interaction")
        st.caption("Config: 7 High-Precision Features")
        st.caption("Target: Import Resilience")
        
    st.divider()
    st.caption("v5.2 Champion Build | Thesis Artifact")

# ==========================================
# 4. TAB SYSTEM
# ==========================================
# We define the 5 core modules of the dashboard
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📊 Overview", 
    "🎮 Simulator", 
    "📈 Performance", 
    "🧠 Evidence Suite", 
    "🔮 Forecast"
])

# --- TAB 1: EXECUTIVE SUMMARY ---
with tab1:
    st.header("Malaysian Seafood Resilience Audit")
    st.write("Quantitative analysis of price volatility drivers using **Explainable Boosting Machines (EBM)**.")
    
    # Dynamic KPI Cards (Updates based on Sidebar Selection)
    c1, c2, c3 = st.columns(3)
    
    if "Kembung" in species_choice:
        # KEMBUNG METRICS (From Audit: 96.76%)
        with c1: 
            st.metric(
                "Model Precision (Week 1)", 
                f"{k_stats.get('Structural_MAE', '0.54')} RM", 
                delta=f"{k_stats.get('Accuracy', '96.76')}% Accuracy"
            )
        with c2: 
            st.metric(
                "Operational Horizon", 
                "8 Weeks", 
                delta="-0.03 RM Accuracy Cost", 
                delta_color="off",
                help="Time period before forecast accuracy degrades significantly."
            )
        with c3: 
            st.metric(
                "Primary Driver", 
                "Domestic Fuel", 
                "RON97 + Tides"
            )
        
        st.divider()
        st.success("""
        **🏆 Policy Verdict:** Valid for **Monthly Review**. 
        Kembung retains **>96% accuracy** even at Week 8, demonstrating strong structural inertia. 
        Prices are driven primarily by domestic fuel costs and local tidal cycles.
        """)
        
    else:
        # SELAR METRICS (From Audit: 97.11%)
        with c1: 
            st.metric(
                "Model Precision (Week 1)", 
                f"{s_stats.get('Structural_MAE', '0.53')} RM", 
                delta=f"{s_stats.get('Accuracy', '97.11')}% Accuracy"
            )
        with c2: 
            st.metric(
                "Operational Horizon", 
                "8 Weeks", 
                delta="-0.04 RM Accuracy Cost", 
                delta_color="off",
                help="Time period before forecast accuracy degrades significantly."
            )
        with c3: 
            st.metric(
                "Primary Driver", 
                "Global Logistics", 
                "USD + Diesel Synergy"
            )
        
        st.divider()
        st.success("""
        **🏆 Policy Verdict:** Valid for **Monthly Review**. 
        Selar demonstrates high resilience to short-term fluctuations due to complex interaction effects (Surgical Features).
        Prices are highly sensitive to the **Synergy of Diesel Price and Currency Strength**.
        """)

# --- TAB 2: SIMULATOR (FORENSIC UTILITY VERSION) ---
with tab2:
    st.header("Price Shock Simulator (Structural Mode)")
    st.caption("Powered by Grand Tournament Champions. Lever configuration reflects specific species drivers.")
    
    # Define Column Layout
    c1, c2 = st.columns([1.2, 1])
    
    if "Kembung" in species_choice:
        # ==========================================
        # KEMBUNG: Benchmark Beater Config (6 Features)
        # ==========================================
        with c1:
            st.subheader("🏛️ Policy War Room")
            st.info("Forensic Insight: Kembung uses the Benchmark Beater Config (6 Features).")
            
            k_ron97 = st.slider("⛽ RON97 Price", 2.0, 5.0, 3.47, help="Primary Inflation Driver")
            k_ron95 = st.slider("🚗 RON95 Price", 1.5, 3.5, 2.05, help="Subsidy Baseline")
            k_diesel = st.slider("🚛 Diesel Price", 1.5, 4.5, 2.15, help="Logistics Base")
            
        with c2:
            st.subheader("🌊 Nature Context")
            k_tide_sb = st.slider("Tide Height (Sabah)", 0.5, 3.0, 1.5)
            k_tide_pk = st.slider("Tide Height (Perak)", 0.5, 3.0, 1.6)
            k_sun_pk = st.slider("Sunset Time (Perak)", 1100, 1200, 1150, help="Fishing Window (Minutes from midnight)")
            
        if st.button("Run Kembung Simulation", type="primary"):
            # INPUT: Matches 'kembung_structural_model.pkl' (No Lags)
            input_df = pd.DataFrame({
                'RON97': [k_ron97], 
                'RON95': [k_ron95], 
                'diesel': [k_diesel], 
                'height_mean_m_sabah': [k_tide_sb], 
                'height_mean_m_perak': [k_tide_pk], 
                'sunset_mean_time_perak': [k_sun_pk]
            })
            pred = k_struct.predict(input_df)[0]
            
            # Result Card
            st.divider()
            col_res, col_alert = st.columns([1, 2])
            with col_res:
                st.metric("Forecasted Price", f"RM {pred:.2f}")
            with col_alert:
                if pred > 16.00:
                    st.error("⚠️ CRITICAL INFLATION RISK")
                elif pred < 11.00:
                    st.success("✅ STABLE MARKET CONDITIONS")
                else:
                    st.warning("⚖️ STANDARD VOLATILITY")

    else:
        # ==========================================
        # SELAR: Surgical Config (7 Features + Interaction Logic)
        # ==========================================
        with c1:
            st.subheader("🏛️ Policy War Room")
            st.info("Forensic Insight: Selar uses Surgical Interaction Features (7 Inputs).")
            
            s_usd = st.slider("🇺🇸 MYR/USD Rate", 3.5, 5.5, 4.6, help="Critical Driver: Import Power")
            s_ron97 = st.slider("⛽ RON97 Price", 2.0, 5.0, 3.47)
            s_ron95 = st.slider("🚗 RON95 Price", 1.5, 3.5, 2.05)
            s_diesel = st.slider("🚛 Diesel Price", 1.5, 4.5, 2.15)
            
        with c2:
            st.subheader("🌊 Nature Context")
            s_tide_pk = st.slider("Tide Height (Perak)", 0.5, 3.0, 1.6, help="Primary Environmental Constraint")
            # Fixed Sunset for Simulation consistency (Standard Fishing Window)
            s_sunset_pk = 1140 
            
        if st.button("Run Selar Simulation", type="primary"):
            # SURGICAL CALCULATION (In-Memory Engineering)
            # This is where the magic happens: Diesel * USD
            econ_press = s_diesel * s_usd
            # Tide * Sunset
            solunar_syn = s_tide_pk * s_sunset_pk
            
            # INPUT: Matches 'selar_structural_model.pkl' (7 Features)
            input_df = pd.DataFrame({
                'RON97': [s_ron97], 
                'myr_per_usd_mean': [s_usd], 
                'RON95': [s_ron95], 
                'diesel': [s_diesel], 
                'econ_pressure_index': [econ_press],
                'height_mean_m_perak': [s_tide_pk],
                'solunar_synergy_perak': [solunar_syn]
            })
            pred = s_struct.predict(input_df)[0]
            
            # Result Card
            st.divider()
            col_res, col_alert = st.columns([1, 2])
            with col_res:
                st.metric("Forecasted Price", f"RM {pred:.2f}")
            with col_alert:
                if pred > 17.50:
                    st.error("⚠️ IMPORT COST SPIKE")
                else:
                    st.success("✅ LOGISTICS STABLE")
# --- TAB 3: PERFORMANCE (FORENSIC SCORECARD) ---
with tab3:
    st.header(f"🎯 {species_choice} Model Performance")
    
    is_kembung = "Kembung" in species_choice
    if is_kembung:
        current_stats = k_stats
        species_name = "Kembung"
        # Define filenames for Kembung Horizon Tests
        file_struct = "kembung_structural_horizon.png"
        file_blind = "kembung_total_blind_horizon.png"
    else:
        current_stats = s_stats
        species_name = "Selar"
        # Define filenames for Selar Horizon Tests
        file_struct = "selar_structural_horizon.png"
        file_blind = "selar_total_blind_horizon.png"

    # 1. KEY PERFORMANCE INDICATORS
    c1, c2, c3 = st.columns(3)
    with c1:
        st.metric("Overall Accuracy", f"{current_stats.get('Accuracy', 'N/A')}%", help="100% - MAPE")
    with c2:
        st.metric("Forensic Error (MAPE)", f"{current_stats.get('MAPE', 'N/A')}%", help="Mean Absolute Percentage Error", delta_color="inverse")
    with c3:
        st.metric("Avg Price Deviation", f"RM {current_stats.get('Structural_MAE', 'N/A')}", help="Mean Absolute Error")

    st.divider()

    # 2. COMPARATIVE HORIZON TEST
    st.subheader("⏳ The Resilience Stress Test (8-Week Horizon)")
    st.caption("Validating the 'Expiration Date' of the forecast. Left: Model Stability. Right: Real-World Volatility.")

    def get_base64_image(path):
        if os.path.exists(path):
            with open(path, "rb") as f:
                return base64.b64encode(f.read()).decode()
        return None

    # Load Images (From Root Directory)
    b64_struct = get_base64_image(file_struct)
    b64_blind = get_base64_image(file_blind)

    h_col1, h_col2 = st.columns(2)
    
    with h_col1:
        st.markdown("**Test A: Scenario Consistency (Inputs Known)**")
        if b64_struct:
            st.markdown(f'<img src="data:image/png;base64,{b64_struct}" style="width:100%; border: 1px solid #ddd; border-radius: 5px;">', unsafe_allow_html=True)
            st.info("✅ **Proof of Physics:** The flat/stable line proves the model is structurally sound. As long as inputs are known, accuracy does not degrade over time.")
        else:
            st.warning(f"File not found: {file_struct}")

    with h_col2:
        st.markdown("**Test B: Total Blackout (Inputs Frozen)**")
        if b64_blind:
            st.markdown(f'<img src="data:image/png;base64,{b64_blind}" style="width:100%; border: 1px solid #ddd; border-radius: 5px;">', unsafe_allow_html=True)
            if is_kembung:
                st.warning("⚠️ **Forensic Insight:** Kembung error spikes immediately. This proves high sensitivity to daily Tides (Nature Penalty).")
            else:
                st.success("🛡️ **Forensic Insight:** Selar error remains relatively stable. This proves high resilience to short-term fluctuations.")
        else:
            st.warning(f"File not found: {file_blind}")
            
    st.divider()
    
    # 3. THE 30-DAY VERDICT
    st.subheader("🏛️ Policy Implication: The 30-Day Rule")
    st.write(f"""
    Based on the divergence between Test A and Test B, we establish a **30-Day Validity Window** for {species_name}. 
    While the model is physically perfect (Test A), the volatility of the real world (Test B) introduces acceptable degradation (+0.05 RM) over 4 weeks.
    """)
    
    rec_col1, rec_col2 = st.columns([1, 3])
    with rec_col1:
        st.metric("Rec. Review Cycle", "Monthly", "Every 30 Days")
    with rec_col2:
        st.info("**Operational Protocol:** Policymakers can rely on this forecast for **4 weeks**. After Day 30, the accumulation of 'Nature Drift' (Tides/Weather) requires a data refresh to maintain >95% accuracy.")

# --- TAB 4: EVIDENCE SUITE ---
with tab4:
    st.header(f"🧠 {species_choice} Forensic Evidence")
    st.write("Deep-dive analytics: Deconstructing the 'Black Box' of seafood pricing.")

    f_dir = "thesis_analytics_images"
    d_dir = "Thesis_Final_Champion_Suite"
    
    is_kembung = "Kembung" in species_choice
    prefix = "kembung" if is_kembung else "selar"
    
    # 1. Decomposition
    st.subheader("📉 Part 1: Time Series Anatomy")
    st.caption("Forensic decomposition of the price into Trend (Inflation) and Observed Reality.")
    
    decomp_file = f"{prefix}_decomposition.png"
    b64_dec = get_base64_image(os.path.join(f_dir, decomp_file))
    
    if b64_dec:
        st.markdown(f'<img src="data:image/png;base64,{b64_dec}" style="width:100%; border: 1px solid #ddd; border-radius: 5px;">', unsafe_allow_html=True)
    else:
        st.warning("Decomposition chart not found.")
        
    st.divider()

    # 2. Structural Feature Importance
    st.subheader("📊 Part 2: Structural Price Drivers")
    st.caption("The hierarchy of influence. Which variables physically move the price the most?")
    
    imp_file = f"{prefix}_structural_importance.png"
    b64_imp = get_base64_image(os.path.join(f_dir, imp_file))
    
    if b64_imp:
        st.markdown(f'<img src="data:image/png;base64,{b64_imp}" style="width:100%; border: 1px solid #ddd; border-radius: 5px;">', unsafe_allow_html=True)
    else:
        st.warning("Feature Importance chart not found.")

    st.divider()

    # 3. Structural Correlation Matrix
    st.subheader("🔗 Part 3: Linear Correlation Matrix")
    st.caption("Raw statistical relationships before AI processing.")
    
    corr_file = f"{prefix}_structural_correlation.png"
    b64_c = get_base64_image(os.path.join(f_dir, corr_file))
    
    if b64_c: 
        st.markdown(f'<img src="data:image/png;base64,{b64_c}" style="width:80%; display: block; margin: auto; border: 1px solid #eee;">', unsafe_allow_html=True)
    else:
        st.warning(f"Correlation chart not found.")

    st.divider()
    
    # 4. PDPs
    st.subheader("🔍 Part 4: Marginal Impact Analysis (PDPs)")
    st.caption("The 'Physics Curves'. These graphs show exactly how the Model reacts to each slider.")
    
    if is_kembung:
        pdp_files = [
            "kembung_pdp_RON97.png", "kembung_pdp_RON95.png", "kembung_pdp_diesel.png",
            "kembung_pdp_height_mean_m_perak.png", "kembung_pdp_height_mean_m_sabah.png", 
            "kembung_pdp_sunset_mean_time_perak.png"
        ]
    else:
        pdp_files = [
            "selar_pdp_myr_per_usd_mean.png", "selar_pdp_RON97.png", "selar_pdp_RON95.png", 
            "selar_pdp_diesel.png", "selar_pdp_height_mean_m_perak.png"
        ]

    cols = st.columns(2)
    for idx, fname in enumerate(pdp_files):
        b64 = get_base64_image(os.path.join(f_dir, fname))
        with cols[idx % 2]:
            if b64:
                st.markdown(f'<img src="data:image/png;base64,{b64}" style="width:100%; margin-bottom:15px; border: 1px solid #f0f0f0; border-radius: 5px;">', unsafe_allow_html=True)
            else:
                st.warning(f"Plot not found: {fname}")

    st.divider()

    # 5. Market Dynamics
    st.subheader("🚀 Part 5: Market Dynamics (Structural Forensics)")
    st.caption("Replacing Hybrid 'Correction' logic with Standalone Structural Signal.")
    
    d_col1, d_col2, d_col3 = st.columns(3)
    
    b64_box = get_base64_image(os.path.join(d_dir, f"{prefix}_boxplot.png"))
    with d_col1:
        st.markdown("**Deliverable #7: Price Arena**")
        if b64_box: 
            st.markdown(f'<img src="data:image/png;base64,{b64_box}" style="width:100%; border: 1px solid #ddd; border-radius: 5px;">', unsafe_allow_html=True)

    b64_res = get_base64_image(os.path.join(d_dir, f"{prefix}_residuals.png"))
    with d_col2:
        st.markdown("**Deliverable #8: Residual Accuracy**")
        if b64_res: 
            st.markdown(f'<img src="data:image/png;base64,{b64_res}" style="width:100%; border: 1px solid #ddd; border-radius: 5px;">', unsafe_allow_html=True)

    b64_vol = get_base64_image(os.path.join(d_dir, f"{prefix}_volatility.png"))
    with d_col3:
        st.markdown("**Deliverable #9: Structural Risk**")
        if b64_vol: 
            st.markdown(f'<img src="data:image/png;base64,{b64_vol}" style="width:100%; border: 1px solid #ddd; border-radius: 5px;">', unsafe_allow_html=True)

# ==========================================
# 5. TAB 5: FORECAST ENGINE (MULTI-HORIZON)
# ==========================================
# RE-IMPORTING DEPENDENCIES
import math
from datetime import timedelta
from astral import moon, sun, LocationInfo

with tab5:
    st.header("🔮 Structural Forecast Engine")
    st.markdown("Generates future price scenarios by combining **Frozen Economic Inputs** (Current Buffer) with **Projected Physics** (Future Tides/Moon).")

    # 1. CONTROLS
    c_hor, c_spec = st.columns(2)
    with c_hor:
        horizon_opt = st.radio("Forecast Horizon:", ["1 Week", "2 Weeks", "3 Weeks", "4 Weeks"], horizontal=True, index=0)
    with c_spec:
        # Defaults to the global sidebar choice, but allows local toggling
        default_idx = 0 if "Kembung" in species_choice else 1
        view_species = st.radio("Species Focus:", ["Kembung", "Selar"], horizontal=True, index=default_idx)

    # 2. CALCULATE TARGET DATE
    weeks_map = {"1 Week": 1, "2 Weeks": 2, "3 Weeks": 3, "4 Weeks": 4}
    weeks_offset = weeks_map[horizon_opt]
    
    try:
        df_buffer = pd.read_csv("Seafood_Security_Buffer.csv")
        latest_row = df_buffer.iloc[-1]
        last_date = pd.to_datetime(latest_row['date'])
        
        # Target Date = Last Scraped Date + (7 days * Weeks)
        target_dt = last_date + timedelta(days=7 * weeks_offset)
        target_date_str = target_dt.strftime('%Y-%m-%d')
        target_week_str = f"Week +{weeks_offset} ({target_dt.strftime('%b %Y')})"
        
    except Exception as e:
        st.error(f"❌ Data Buffer Error: {e}")
        st.stop()

    # 3. PROJECT PHYSICS (ASTRAL ENGINE)
    try:
        # A. MOON PHASE
        phase_days = moon.phase(target_dt)
        tide_force = math.cos(2 * math.pi * (phase_days / 29.53))
        
        # B. CALIBRATED REGIME
        proj_tide_pk = 1.6731 + (tide_force * 0.0934)
        proj_tide_sb = 1.1440 + (tide_force * 0.1324)
        
        # C. SUNSET TIME
        perak_loc = LocationInfo("Lumut", "Malaysia", "Asia/Kuala_Lumpur", 4.2105, 100.63)
        s = sun.sun(perak_loc.observer, date=target_dt)
        sunset_dt = s['sunset'].replace(tzinfo=None) + timedelta(hours=8)
        proj_sunset = sunset_dt.hour * 60 + sunset_dt.minute

    except Exception as e:
        st.error(f"⚠️ Physics Projection Error: {e}")
        st.stop()

    # 4. GENERATE PREDICTIONS
    try:
        # FROZEN ECONOMICS
        curr_diesel = latest_row.get('diesel', 2.15)
        curr_usd = latest_row.get('myr_per_usd_mean', 4.5)
        curr_ron95 = latest_row.get('RON95', 2.05)
        curr_ron97 = latest_row.get('RON97', 3.47)

        # KEMBUNG (Benchmark Config)
        k_input = pd.DataFrame({
            'RON97': [curr_ron97],
            'RON95': [curr_ron95],
            'diesel': [curr_diesel],
            'height_mean_m_sabah': [proj_tide_sb],
            'height_mean_m_perak': [proj_tide_pk],
            'sunset_mean_time_perak': [proj_sunset]
        })
        k_pred = k_struct.predict(k_input)[0]

        # SELAR (Surgical Config)
        s_econ_press = curr_diesel * curr_usd
        s_solunar_syn = proj_tide_pk * 1140 
        
        s_input = pd.DataFrame({
            'RON97': [curr_ron97],
            'myr_per_usd_mean': [curr_usd],
            'RON95': [curr_ron95],
            'diesel': [curr_diesel],
            'econ_pressure_index': [s_econ_press],
            'height_mean_m_perak': [proj_tide_pk],
            'solunar_synergy_perak': [s_solunar_syn]
        })
        s_pred = s_struct.predict(s_input)[0]

    except Exception as e:
        st.error(f"Model Prediction Error: {e}")
        st.stop()

    # 5. ERROR MARGIN LOGIC (Derived from Astral Horizon Test)
    # These values come directly from the validation script output
    k_margins = {1: 0.53, 2: 0.53, 3: 0.55, 4: 0.57}
    s_margins = {1: 0.53, 2: 0.57, 3: 0.60, 4: 0.60}
    
    k_err = k_margins.get(weeks_offset, 0.60)
    s_err = s_margins.get(weeks_offset, 0.65)

    # 6. DISPLAY DASHBOARD
    st.divider()
    
    # A. Headline Numbers
    m1, m2 = st.columns(2)
    with m1:
        st.metric("Forecast Target", target_date_str, target_week_str)
    
    with m2:
        if view_species == "Kembung":
            st.metric(
                "Kembung Price", 
                f"RM {k_pred:.2f}", 
                delta=f"± {k_err:.2f} RM (Margin)",
                delta_color="off", # Gray color to indicate range/uncertainty
                help="Margin of Error derived from Astral Horizon Stress Test"
            )
        else:
            st.metric(
                "Selar Price", 
                f"RM {s_pred:.2f}", 
                delta=f"± {s_err:.2f} RM (Margin)",
                delta_color="off",
                help="Margin of Error derived from Astral Horizon Stress Test"
            )

    st.divider()

    # B. The Deep Dive (Specific Species)
    if view_species == "Kembung":
        st.subheader("🐟 Kembung Structural Inputs")
        st.write(f"Variables used for **{target_week_str}** prediction.")
        
        k_df = pd.DataFrame({
            'Feature': ['RON95 (Frozen)', 'RON97 (Frozen)', 'Diesel (Frozen)', 'Tide Sabah (Proj)', 'Tide Perak (Proj)', 'Sunset (Proj)', 'Moon Phase'],
            'Value': [
                f"RM {curr_ron95:.2f}",
                f"RM {curr_ron97:.2f}",
                f"RM {curr_diesel:.2f}", 
                f"{proj_tide_sb:.2f} m", 
                f"{proj_tide_pk:.2f} m", 
                f"{int(proj_sunset)} min", 
                f"{phase_days:.1f}/29.5"
            ],
            'Type': ['Economic (Buffer)', 'Economic (Buffer)', 'Economic (Buffer)', 'Physics (Astral)', 'Physics (Astral)', 'Physics (Astral)', 'Context']
        })
        st.table(k_df)
        
    else:
        st.subheader("🐠 Selar Structural Inputs")
        st.write(f"Variables used for **{target_week_str}** prediction.")
        
        s_df = pd.DataFrame({
            'Feature': ['RON95 (Frozen)', 'RON97 (Frozen)', 'Diesel (Frozen)', 'USD Rate (Frozen)', 'Tide Perak (Proj)'],
            'Value': [
                f"RM {curr_ron95:.2f}",
                f"RM {curr_ron97:.2f}",
                f"RM {curr_diesel:.2f}", 
                f"{curr_usd:.2f}", 
                f"{proj_tide_pk:.2f} m"
            ],
            'Type': ['Economic (Buffer)', 'Economic (Buffer)', 'Economic (Buffer)', 'Economic (Buffer)', 'Physics (Astral)']
        })
        st.table(s_df)
        